### ISSUE TITLE
gRoot --oneline

### ISSUE THREAD

**Issue by r1walz** [sdslabs/gRoot#18]
https://github.com/sdslabs/gRoot/blob/f3b10b97b4f51749c161c8968031b1db996f98b0/src/main.kt#L1-L3

Suggestion **:**
```kt
fun main(args: Array<String>) = println("I am gRoot")
```

Why write unnecessarily long code? Use kotlin's oneliners!

**Comment by uttu357** [comment]
Would love a PR! @r1walz
